apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: danprojectgithub-system-entry
  namespace: danprojectgithub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: danprojectgithub-system-entry
    spec:
      containers:
        - name: nginx-container
          imagePullPolicy: IfNotPresent
          image: tharanirajan/danprojectgithub-system-entry:1.0
          ports:
            - name: http-port
              containerPort: 80