apiVersion: v1
kind: Service
metadata:
 labels:
   name: danprojectgithub-app-db
 name: danprojectgithub-app-db
 namespace: danprojectgithub
spec:
 type: NodePort
 ports:
 - name: mongo-db
   port: 27017
   targetPort: 27017
 selector:
   name: danprojectgithub-app-db