apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: danprojectgithub-app-db
  namespace: danprojectgithub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: danprojectgithub-app-db
    spec:
      containers:
        - name: mongo-container
          imagePullPolicy: Always
          image: mongo:3.2
          ports:
            - name: http-port
              containerPort: 27017
          volumeMounts:
            - name: mongo
              mountPath: /data/db
      volumes:
        - name: mongo
          persistentVolumeClaim:
            claimName: danprojectgithub-app-mongo-data