apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: danprojectgithub-app-mongo-data
  namespace: danprojectgithub
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi