apiVersion: v1
kind: Service
metadata:
  name: danprojectgithub-telemetry
  labels:
    app: danprojectgithub-telemetry
  namespace: danprojectgithub  
spec:
  type: NodePort
  ports:
    - name: vault
      targetPort: 8200
      port: 8200
  selector:
    app: danprojectgithub-telemetry