apiVersion: v1
kind: Service
metadata:
  name: danprojectgithub-app
  namespace: danprojectgithub
spec:
  type: NodePort
  ports:
  - name: node-app
    port: 3000
    targetPort: 3000
  selector:
    app: danprojectgithub-app